

/*


CREATE SCHEMA `Ninak` ;
-- CREATE DATABASE `Ninak` ;
DROP TABLE IF EXISTS `account`;
CREATE TABLE `account` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `old_password` varchar(255) DEFAULT NULL,
  `wrong_login_attempt` int(11) DEFAULT NULL,
  `today_login_attempt` int(11) DEFAULT NULL,
  `is_now_login` int(1) DEFAULT NULL,
  `date` varchar(20) DEFAULT NULL,
  `time` time DEFAULT NULL,
  `timestamp` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=600855 DEFAULT CHARSET=utf8;

INSERT INTO account(username,password) values('rjzevallos.salazar@gmail.com','123456');
*/

-- MySQL Script generated by MySQL Workbench
-- Mon Jul  6 00:07:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Ninak
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ninak
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ninak`;
CREATE SCHEMA IF NOT EXISTS `Ninak` DEFAULT CHARACTER SET utf8 ;
USE `Ninak` ;

-- -----------------------------------------------------
-- Table `Ninak`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `old_password` VARCHAR(255) NULL,
  `wrong_login_attempt` INT NULL,
  `today_login_attempt` VARCHAR(45) NULL,
  `is_now_login` INT NULL,
  `date` VARCHAR(20) NULL,
  `time` DATETIME NULL,
  `timestamp` VARCHAR(20) NULL,
  PRIMARY KEY (`idAccount`))
ENGINE = InnoDB;

INSERT INTO `Ninak`.`Account` (username,password) values('rjzevallos.salazar@gmail.com','ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413');
-- -----------------------------------------------------
-- Table `Ninak`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `idPersona_idx` (`idPersona` ASC),
  CONSTRAINT `idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `Ninak`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Asignatura` (
  `idAsignatura` INT NOT NULL AUTO_INCREMENT,
  `Asignatura` VARCHAR(100) NULL,
  `fechaCreacion` DATETIME NULL,
  `creadoPor` INT NULL,
  `Descripcion` VARCHAR(500) NULL,
  `idGrado` INT NOT NULL,
  PRIMARY KEY (`idAsignatura`),
  INDEX `idGrado_idx` (`idGrado` ASC),
  CONSTRAINT `idGrado`
    FOREIGN KEY (`idGrado`)
    REFERENCES `Ninak`.`Grado` (`idGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`AsignaturaXPeriodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`AsignaturaXPeriodo` (
  `idAsignaturaXPeriodo` INT NOT NULL AUTO_INCREMENT,
  `IdAsignatura` INT NOT NULL,
  `IdPeriodo` INT NOT NULL,
  `idProfesor` INT NOT NULL,
  PRIMARY KEY (`idAsignaturaXPeriodo`),
  INDEX `idAsignatura_idx` (`IdAsignatura` ASC),
  INDEX `idPeriodo_idx` (`IdPeriodo` ASC),
  INDEX `idProfesor_idx` (`idProfesor` ASC),
  CONSTRAINT `idAsignatura`
    FOREIGN KEY (`IdAsignatura`)
    REFERENCES `Ninak`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPeriodo`
    FOREIGN KEY (`IdPeriodo`)
    REFERENCES `Ninak`.`Periodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProfesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `Ninak`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`colegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`colegio` (
  `idcolegio` INT NOT NULL AUTO_INCREMENT,
  `colegio` VARCHAR(1000) NULL,
  `fechaCreacion` DATETIME NULL,
  `creadoPor` INT NULL,
  PRIMARY KEY (`idcolegio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `Curso` VARCHAR(100) NULL,
  `fechaCreacion` DATETIME NULL,
  `creadoPor` INT NULL,
  `NotaFinal` DECIMAL(4,2) NULL,
  `idAlumno` INT NOT NULL,
  `idAsignatura` INT NOT NULL,
  `Observacion` VARCHAR(500) NULL,
  `idCalificacion` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `idAlumno_idx` (`idAlumno` ASC),
  INDEX `idAsignatura_idx` (`idAsignatura` ASC),
  CONSTRAINT `idAlumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `Ninak`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Asignatura`
    FOREIGN KEY (`idAsignatura`)
    REFERENCES `Ninak`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Evaluacion` (
  `idEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `evaluacion` VARCHAR(255) NULL,
  `notaEvaluacion` DECIMAL(10,2) NULL,
  `peso` INT NULL,
  `fechaCreacion` DATETIME NULL,
  `creadoPor` INT NULL,
  `fechaModificacion` DATETIME NULL,
  `modificadoPor` INT NULL,
  PRIMARY KEY (`idEvaluacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`EvaluacioXAlumnoXCusrso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`EvaluacioXAlumnoXCusrso` (
  `idEvaluacioXAlumnoXCusrso` INT NOT NULL AUTO_INCREMENT,
  `idEvaluacion` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `idAlumno` INT NOT NULL,
  PRIMARY KEY (`idEvaluacioXAlumnoXCusrso`),
  INDEX `idEvaluacion_idx` (`idEvaluacion` ASC),
  INDEX `idCurso_idx` (`idCurso` ASC),
  INDEX `idAlumno_idx` (`idAlumno` ASC),
  CONSTRAINT `idEvaluacion`
    FOREIGN KEY (`idEvaluacion`)
    REFERENCES `Ninak`.`Evaluacion` (`idEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `Ninak`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Alumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `Ninak`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Grado` (
  `idGrado` INT NOT NULL AUTO_INCREMENT,
  `Grado` VARCHAR(45) NULL,
  `idNivelEducativo` INT NOT NULL,
  PRIMARY KEY (`idGrado`),
  INDEX `idNivelEducativo_idx` (`idNivelEducativo` ASC),
  CONSTRAINT `idNivelEducativo`
    FOREIGN KEY (`idNivelEducativo`)
    REFERENCES `Ninak`.`NivelEducativo` (`idNivelEducativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `Material` VARCHAR(1000) NULL,
  `idTipoMaterial` INT NOT NULL,
  PRIMARY KEY (`idMaterial`),
  INDEX `idTipoMaterial_idx` (`idTipoMaterial` ASC),
  CONSTRAINT `idTipoMaterial`
    FOREIGN KEY (`idTipoMaterial`)
    REFERENCES `Ninak`.`TipoMaterial` (`idTipoMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`NivelEducativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`NivelEducativo` (
  `idNivelEducativo` INT NOT NULL AUTO_INCREMENT,
  `NivelEducativo` VARCHAR(100) NULL,
  `fechaCreacion` DATETIME NULL,
  `creadoPor` INT NULL,
  PRIMARY KEY (`idNivelEducativo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Periodo` (
  `idPeriodo` INT NOT NULL AUTO_INCREMENT,
  `Periodo` VARCHAR(45) NULL,
  `idMaterial` INT NOT NULL,
  PRIMARY KEY (`idPeriodo`),
  INDEX `idMaterial_idx` (`idMaterial` ASC),
  CONSTRAINT `idMaterial`
    FOREIGN KEY (`idMaterial`)
    REFERENCES `Ninak`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `apellidoPat` VARCHAR(100) NULL,
  `apellidoMat` VARCHAR(100) NULL,
  `fechaNac` DATETIME NULL,
  `correo` VARCHAR(100) NULL,
  `fechaCreacion` DATETIME NULL,
  `creadoPor` INT NULL,
  `fechaModificacion` DATETIME NULL,
  `modificadoPor` INT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`Profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idProfesor`),
  INDEX `idPersona_idx` (`idPersona` ASC),
  CONSTRAINT `id_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `Ninak`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ninak`.`TipoMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ninak`.`TipoMaterial` (
  `idTipoMaterial` INT NOT NULL AUTO_INCREMENT,
  `TipoMaterial` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoMaterial`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

